ASSUME CS:CODE,DS:DATA
DATA SEGMENT
    N DB ?
    MSG1 DB 0AH,0DH, "ENTER NUMBER OF ELEMENTS: $"
    MSG2 DB 0AH,0DH, "ENTER THE ELEMENTS: $"
    MSG3 DB 0AH,0DH, "SMALLEST NUMBER IS: $"
    MSG4 DB 0AH,0DH, "LARGEST NUMBER IS: $"
DATA ENDS
CODE SEGMENT
START:
    MOV AX,DATA
    MOV DS,AX
    LEA DX,MSG1
    MOV AH,09H
    INT 21H
    MOV AH,01H
    INT 21H
    MOV N,AL
    SUB N,30H
    MOV BL,0AAH
    MOV BH,0H
    LABEL1:
        LEA DX,MSG2
        MOV AH,09H
        INT 21H
        MOV AH,01H
        INT 21H
        MOV DL,AL
        CMP DL,BL
        JNC LABEL2
        MOV BL,DL
        JMP LABEL3
    LABEL2:
        CMP DL,BH
        JC LABEL3
        MOV BH,DL
    LABEL3:
        DEC N
        JNZ LABEL1
    LEA DX,MSG3
    MOV AH,09H
    INT 21H
    MOV DL,BL
    MOV AH,02H
    INT 21H
    LEA DX,MSG4
    MOV AH,09H
    INT 21H
    MOV DL,BH
    MOV AH,02H
    INT 21H
    MOV AH,4CH
    INT 21H
CODE ENDS
END START



