ASSUME CS:CODE,DS:DATA
DATA SEGMENT
    MSG1 DB 0AH,0DH, "ENTER STRING: $"
    MSG2 DB 0AH,0DH, "PALINDROME: $"
    MSG3 DB 0AH,0DH, "NOT PALINDROME: $"
    STR1 DB 50 DUP("$")
DATA ENDS
CODE SEGMENT
START:
    MOV AX,DATA
    MOV DS,AX
    LEA DX,MSG1
    MOV AH,09H
    INT 21H
    LEA SI,STR1
    INPUT:  MOV AH,01H
    INT 21H
    CMP AL,13
    JE L1
    MOV [SI],AL
    INC SI
    JMP INPUT
    L1: LEA DI,STR1
    DEC SI
    L2: CMP SI,DI
    JL L4
    MOV AL,[SI]
    MOV BL,[DI]
    CMP AL,BL
    JNE L3
    INC DI
    DEC SI
    JMP L2
    L3: LEA DX,MSG3
    MOV AH,09H
    INT 21H
    JMP L5
    L4: LEA DX,MSG2
    MOV AH,09H
    INT 21H
    L5: MOV AH,4CH
    INT 21H
CODE ENDS
END START

