ASSUME CS:CODE,DS:DATA
DATA SEGMENT
    MSG1 DB 0AH,0DH, "ENTER STRING: $"
    MSG2 DB 0AH,0DH, "COUNT OF VOWELS: $"
    VOW DB 5 DUP('A','E','I','O','U')
DATA ENDS
CODE SEGMENT
START:
    MOV AX,DATA
    MOV DS,AX
    MOV DI,OFFSET VOW
    MOV BL,00H
    LEA DX,MSG1
    MOV AH,09H
    INT 21H
INPUT:
    MOV AH,01H
    INT 21H
    MOV CL,05H

CHECK:
    CMP AL,[DI]
    JNE LABEL1
    INC BL
    MOV BYTE PTR [DI],00H
    JMP INPUT

LABEL1:
    INC DI
    DEC CL
    CMP CL,00H
    JNE CHECK
    LEA DX,MSG2
    MOV AH,09H
    INT 21H
    MOV DL,BL
    ADD DL,30H
    MOV AH,02H
    INT 21H
    MOV AH,4CH
    INT 21H
        
CODE ENDS
END START
